--Script in charge of integrating the foreign keys to the database

ALTER TABLE PATIENT_PATHOLOGIES
ADD CONSTRAINT PATIENT_PATHOLOGIES_PATIENT_FK FOREIGN KEY (Patient)
REFERENCES PATIENT (Ssn);
GO

ALTER TABLE PATIENT_PATHOLOGIES
ADD CONSTRAINT PATIENT_PATHOLOGIES_PATHOLOGY_FK FOREIGN KEY (Pathology)
REFERENCES PATHOLOGY (Id);
GO

ALTER TABLE PROVINCE_STATE_REGION
ADD CONSTRAINT PROVINCE_STATE_REGION_COUNTRY_FK FOREIGN KEY (Country)
REFERENCES COUNTRY (Name);
GO

ALTER TABLE PATIENT_MEDICATION
ADD CONSTRAINT PATIENT_MEDICATION_PATIENT_FK FOREIGN KEY (Patient)
REFERENCES PATIENT (Ssn);
GO

ALTER TABLE PATIENT_MEDICATION
ADD CONSTRAINT PATIENT_MEDICATION_MEDICATION_FK FOREIGN KEY (Medication)
REFERENCES MEDICATION (Id);
GO

ALTER TABLE ENFORCES
ADD CONSTRAINT ENFORCES_COUNTRY_FK FOREIGN KEY (Country)
REFERENCES COUNTRY (Name);
GO

ALTER TABLE ENFORCES
ADD CONSTRAINT ENFORCES_SANITARY_MEASUREMENTS_FK FOREIGN KEY (Measurement)
REFERENCES SANITARY_MEASUREMENTS (Id);
GO

ALTER TABLE PATIENT
ADD CONSTRAINT PATIENT_COUNTRY_C_FK FOREIGN KEY (Country)
REFERENCES COUNTRY (Name);
GO

ALTER TABLE PATIENT
ADD CONSTRAINT PATIENT_COUNTRY_N_FK FOREIGN KEY (Nationality)
REFERENCES COUNTRY (Name)
GO

ALTER TABLE PATIENT
ADD CONSTRAINT PATIENT_HOSPITAL_FK FOREIGN KEY (Hospital)
REFERENCES HOSPITAL (Id);
GO

ALTER TABLE PATIENT_STATE
ADD CONSTRAINT PATIENT_STATE_STATE_FK FOREIGN KEY (State)
REFERENCES STATE (Id);
GO

ALTER TABLE PATIENT_STATE
ADD CONSTRAINT PATIENT_STATE_PATIENT_FK FOREIGN KEY (Patient)
REFERENCES PATIENT (Ssn);
GO

ALTER TABLE HOSPITAL
ADD CONSTRAINT HOSPITAL_COUNTRY_FK FOREIGN KEY (Country)
REFERENCES COUNTRY (Name);
GO

ALTER TABLE CONTACT
ADD CONSTRAINT CONTACT_PERSON_FK FOREIGN KEY (Person)
REFERENCES PERSON (Ssn);
GO

ALTER TABLE CONTACT
ADD CONSTRAINT CONTACT_PATIENT_FK FOREIGN KEY (Patient)
REFERENCES PATIENT (Ssn);
GO

ALTER TABLE COUNTRY
ADD CONSTRAINT COUNTRY_CONTINENT_FK FOREIGN KEY (ContinentName)
REFERENCES CONTINENT (Name);
GO