--Script in charge of creating trigger for the state table

CREATE TRIGGER STATE_ALTERATION_TRIGGER
ON STATE
AFTER INSERT, DELETE, UPDATE
AS
IF EXISTS (SELECT *
           FROM inserted AS i
           WHERE i.Id < 4
           UNION
           SELECT *
           FROM deleted AS d
           WHERE d.Id < 4
          )
BEGIN
ROLLBACK TRANSACTION
RETURN
END;
GO

CREATE TRIGGER STATE_DELETION_FROM_PATIENT_TRIGGER
ON PATIENT_STATE
AFTER DELETE
AS
BEGIN
ROLLBACK TRANSACTION
RETURN
END;
GO