CREATE PROCEDURE GetCountryMeasures
AS
SELECT ENFORCES.Country, SANITARY_MEASUREMENTS.Name, ENFORCES.StartDate, ENFORCES.FinalDate, ENFORCES.Id FROM ENFORCES
INNER JOIN SANITARY_MEASUREMENTS ON SANITARY_MEASUREMENTS.Id = ENFORCES.Measurement;
GO

CREATE PROCEDURE InsertCountryMeasures @Country VARCHAR(30), @Measurement VARCHAR(15), @StartDate DATE, @FinalDate DATE
AS
DECLARE @SMID AS INT
SELECT @SMID = SANITARY_MEASUREMENTS.Id FROM SANITARY_MEASUREMENTS
WHERE @Measurement = SANITARY_MEASUREMENTS.Name
INSERT INTO ENFORCES (Country, Measurement, StartDate, FinalDate)
VALUES (@Country, @SMID, @StartDate, @FinalDate);
GO

CREATE PROCEDURE UpdateCountryMeasures @Country VARCHAR(30), @Measurement VARCHAR(15), @StartDate DATE, @FinalDate DATE, @Id INT
AS
DECLARE @SMID AS INT
SELECT @SMID = SANITARY_MEASUREMENTS.Id FROM SANITARY_MEASUREMENTS
WHERE @Measurement = SANITARY_MEASUREMENTS.Name
UPDATE ENFORCES
SET ENFORCES.Country = @Country, ENFORCES.Measurement = @SMID, ENFORCES.StartDate = @StartDate, ENFORCES.FinalDate = @FinalDate
WHERE ENFORCES.Id = @Id;
GO