CREATE PROCEDURE DeleteContactsOlderThan14Days
AS
DECLARE @PersonSsn VARCHAR (15)
SELECT @PersonSsn = CONTACT.Person FROM CONTACT
WHERE CONTACT.Date < GETDATE() - 14
DELETE FROM CONTACT
WHERE CONTACT.Person = @PersonSsn
DELETE FROM PERSON
WHERE PERSON.Ssn = @PersonSsn;
GO

CREATE PROCEDURE CheckContacts
AS
BEGIN
WHILE (1 = 1)
  BEGIN
    WAITFOR DELAY '12:00:00'
    EXEC DeleteContactsOlderThan14Days
  END
END;
GO

