INSERT INTO COUNTRY (Name, ContinentName, EMail)
VALUES ('Afghanistan', 'Asia', 'afghadm@pdb.com'),
       ('Angola', 'Africa', 'angadm@pdb.com'),
       ('Albania', 'Europe', 'albadm@pdb.com'),
       ('United Arab Emirates', 'Asia', 'uaeadm@pdb.com'),
       ('Argentina', 'South America', 'argadm@pdb.com'),
       ('Armenia', 'Asia', 'armadm@pdb.com'),
       ('Australia', 'Oceania', 'austraadm@pdb.com'),
       ('Austria', 'Europe', 'austriadm@pdb.com'),
       ('Azerbaijan', 'Asia', 'azeradm@pdb.com'),
       ('Burundi', 'Africa', 'buradm@pdb.com'),
       ('Belgium', 'Europe', 'belgadm@pdb.com'),
       ('Benin', 'Africa', 'benadm@pdb.com'),
       ('Burkina Faso', 'Africa', 'bfadm@pdb.com'),
       ('Bangladesh', 'Asia', 'bangadm@pdb.com'),
       ('Bulgaria', 'Europe', 'bulgadm@pdb.com'),
       ('Bahamas', 'North America', 'bahamd@pdb.com'),
       ('Bosnia and Herz.', 'Europe', 'boaheadm@pdb.com'),
       ('Belarus', 'Europe', 'beladm@pdb.com'),
       ('Belize', 'North America', 'beliadm@pdb.com'),
       ('Bolivia', 'South America', 'boliadm@pdb.com'),
       ('Brazil', 'South America', 'brzadm@pdb.com'),
       ('Brunei', 'Asia', 'brunadm@pdb.com'),
       ('Bhutan', 'Asia', 'bhutadm@pdb.com'),
       ('Botswana', 'Africa', 'botsadm@pdb.com'),
       ('Central African Rep.', 'Africa', 'caradm@pdb.com'),
       ('Canada', 'North America', 'canadm@pdb.com'),
       ('Chile', 'South America', 'chiladm@pdb.com'),
       ('China', 'Asia', 'chinadm@pdb.com'),
       ('Cameroon', 'Africa', 'cameadm@pdb.com'),
       ('Congo', 'Africa', 'congadm@pdb.com'),
       ('Colombia', 'South America', 'colomadm@pdb.com'),
       ('Costa Rica', 'Central America', 'cradm@pdb.com'),
       ('Cuba', 'North America', 'cubadm@pdb.com'),
       ('Cyprus', 'Asia', 'cypadm@pdb.com'),
       ('Czech Rep.', 'Europe', 'czradm@pdb.com'),
       ('Djibouti', 'Africa', 'djibadm@pdb.com'),
       ('Germany', 'Europe', 'germadm@pdb.com'),
       ('Switzerland', 'Europe', 'swiadm@pdb.com'),
       ('Denmark', 'Europe', 'denadm@pdb.com'),
       ('Dominican Rep.', 'North America', 'drepadm@pdb.com'),
       ('Algeria', 'Africa', 'alge@pdb.com'),
       ('Ecuador', 'South America', 'ecuadm@pdb.com'),
       ('Egypt', 'Africa', 'egypadm@pdb.com'),
       ('Eritrea', 'Africa', 'eritadm@pdb.com'),
       ('Spain', 'Europe', 'spaiadm@pdb.com'),
       ('Estonia', 'Europe', 'estoadm@pdb.com'),
       ('Ethiopia', 'Africa', 'ethioadm@pdb.com'),
       ('Finland', 'Europe', 'finadm@pdb.com'),
       ('Fiji', 'Oceania', 'fijiadm@pdb.com'),
       ('Falkland Is.', 'South America', 'falkisadm@pdb.com'),
       ('France', 'Europe', 'fradm@pdb.com'),
       ('Gabon', 'Africa', 'gaboadm@pdb.com'),
       ('United Kingdom', 'Europe', 'ukadm@pdb.com'),
       ('Georgia', 'Asia', 'gergadm@pdb.com'),
       ('Ghana', 'Africa', 'ghanadm@pdb.com'),
       ('Guinea', 'Africa', 'guinadm@pdb.com'),
       ('Gambia', 'Africa', 'gambadm@pdb.com'),
       ('Greece', 'Europe', 'greecadm@pdb.com'),
       ('Greenland', 'North America', 'greenadm@pdb.com'),
       ('Guatemala', 'Central America', 'guatadm@pdb.com'),
       ('Guyana', 'South America', 'guyadm@pdb.com'),
       ('Honduras', 'Central America', 'hondadm@pdb.com'),
       ('Croatia', 'Europe', 'croadm@pdb.com'),
       ('Haiti', 'Central America', 'haitadm@pdb.com'),
       ('Hungary', 'Europe', 'hungadm@pdb.com'),
       ('Indonesia', 'Asia', 'indoadm@pdb.com'),
       ('India', 'Asia', 'indiadm@pdb.com'),
       ('Ireland', 'Europe', 'ireadm@pdb.com'),
       ('Iran', 'Asia', 'iranadm@pdb.com'),
       ('Iraq', 'Asia', 'iraqadm@pdb.com'),
       ('Iceland', 'Europe', 'iceadm@pdb.com'),
       ('Israel', 'Asia', 'isradm@pdb.com'),
       ('Italy', 'Europe', 'italadm@pdb.com'),
       ('Jamaica', 'North America', 'jamadm@pdb.com'),
       ('Jordan', 'Asia', 'jordadm@pdb.com'),
       ('Japan', 'Asia', 'japadm@pdb.com'),
       ('Kazakhstan', 'Asia', 'kazakadm@pdb.com'),
       ('Kenya', 'Africa', 'kenyadm@pdb.com'),
       ('Kyrgyzstan', 'Asia', 'kyrgyadm@pdb.com'),
       ('Cambodia', 'Asia', 'cambadm@pdb.com'),
       ('Korea', 'Asia', 'koradm@pdb.com'),
       ('Kosovo', 'Europe', 'kosoadm@pdb.com'),
       ('Kuwait', 'Asia', 'kuwadm@pdb.com'),
       ('Lao PDR', 'Asia', 'laoadm@pdb.com'),
       ('Lebanon', 'Asia', 'lenadm@pdb.com'),
       ('Liberia', 'Africa', 'libeadm@pdb.com'),
       ('Libya', 'Africa', 'libyadm@pdb.com'),
       ('Sri Lanka', 'Asia', 'sriladm@pdb.com'),
       ('Lesotho', 'Africa', 'lesoadm@pdb.com'),
       ('Lithuania', 'Europe', 'litadm@pdb.com'),
       ('Luxembourg', 'Europe', 'luxemadm@pdb.com'),
       ('Latvia', 'Europe', 'latadm@pdb.com'),
       ('Morocco', 'Africa', 'moroadm@pdb.com'),
       ('Moldova', 'Europe', 'moladm@pdb.com'),
       ('Madagascar', 'Africa', 'madadm@pdb.com'),
       ('Mexico', 'North America', 'mexadm@pdb.com'),
       ('Macedonia', 'Europe', 'maceadm@pdb.com'),
       ('Mali', 'Africa', 'maliadm@pdb.com'),
       ('Myanmar', 'Asia', 'myanadm@pdb.com'),
       ('Montenegro', 'Europe', 'monteadm@pdb.com'),
       ('Mongolia', 'Asia', 'mongoadm@pdb.com'),
       ('Mozambique', 'Africa', 'mozadm@pdb.com'),
       ('Mauritania', 'Africa', 'mauadm@pdb.com'),
       ('Malawi', 'Africa', 'malawiadm@pdb.com'),
       ('Malaysia', 'Asia', 'malayadm@pdb.com'),
       ('Namibia', 'Africa', 'namiadm@pdb.com'),
       ('New Caledonia', 'Oceania', 'necaladm@pdb.com'),
       ('Niger', 'Africa', 'nigeradm@pdb.com'),
       ('Nigeria', 'Africa', 'nigeriadm@pdb.com'),
       ('Nicaragua', 'Central America', 'nicadm@pdb.com'),
       ('Netherlands', 'Europe', 'netheradm@pdb.com'),
       ('Norway', 'Europe', 'noradm@pdb.com'),
       ('Nepal', 'Asia', 'nepadm@pdb.com'),
       ('New Zealand', 'Oceania', 'nzadm@pdb.com'),
       ('Oman', 'Asia', 'omadm@pdb.com'),
       ('Pakistan', 'Asia', 'pakadm@pdb.com'),
       ('Panama', 'Central America', 'panadm@pdb.com'),
       ('Peru', 'South America', 'peruadm@pdb.com'),
       ('Philippines', 'Asia', 'philipadm@pdb.com'),
       ('Poland', 'Europe', 'poladm@pdb.com'),
       ('Puerto Rico', 'North America', 'puriadm@pdb.com'),
       ('Dem. Rep. Korea', 'Asia', 'drkoadm@pdb.com'),
       ('Portugal', 'Europe', 'portadm@pdb.com'),
       ('Paraguay', 'South America', 'paradm@pdb.com'),
       ('Palestine', 'Asia', 'palesadm@pdb.com'),
       ('Qatar', 'Asia', 'qatadm@pdb.com'),
       ('Romania', 'Europe', 'romadm@pdb.com'),
       ('Russia', 'Asia', 'russadm@pdb.com'),
       ('Rwanda', 'Africa', 'rwadm@pdb.com'),
       ('W. Sahara', 'Africa', 'wsadm@pdb.com'),
       ('Saudi Arabia', 'Asia', 'sauaradm@pdb.com'),
       ('Sudan', 'Africa', 'sudadm@pdb.com'),
       ('Senegal', 'Africa', 'seneadm@pdb.com'),
       ('Solomon Is.', 'Oceania', 'soloadm@pdb.com'),
       ('Sierra Leone', 'Africa', 'sieleadm@pdb.com'),
       ('El Salvador', 'Central America', 'elsadm@pdb.com'),
       ('Somaliland', 'Africa', 'somaliladm@pdb.com'),
       ('Somalia', 'Africa', 'somadm@pdb.com'),
       ('Serbia', 'Europe', 'serbiadm@pdb.com'),
       ('Suriname', 'South America', 'suriadm@pdb.com'),
       ('Slovakia', 'Europe', 'slovadm@pdb.com'),
       ('Slovenia', 'Europe', 'solveadm@pdb.com'),
       ('Sweden', 'Europe', 'swedadm@pdb.com'),
       ('Swaziland', 'Africa', 'swaziadm@pdb.com'),
       ('Syria', 'Asia', 'syradm@pdb.com'),
       ('Chad', 'Africa', 'chadadm@pdb.com'),
       ('Togo', 'Africa', 'togoadm@pdb.com'),
       ('Thailand', 'Asia', 'thaiadm@pdb.com'),
       ('Tajikistan', 'Asia', 'tajiadm@pdb.com'),
       ('Turkmenistan', 'Asia', 'turkmeadm@pdb.com'),
       ('Timor-Leste', 'Asia', 'tileadm@pdb.com'),
       ('Trinidad and Tobago', 'North America', 'triatoadm@pdb.com'),
       ('Tunisia', 'Africa', 'tuniadm@pdb.com'),
       ('Turkey', 'Asia', 'turkadm@pdb.com'),
       ('Taiwan', 'Asia', 'taiwadm@pdb.com'),
       ('Tanzania', 'Africa', 'tanzadm@pdb.com'),
       ('Uganda', 'Africa', 'ugadm@pdb.com'),
       ('Ukraine', 'Europe', 'ukradm@pdb.com'),
       ('Uruguay', 'South America', 'uruadm@pdb.com'),
       ('United States', 'North America', 'usadm@pdb.com'),
       ('Uzbekistan', 'Asia', 'uzbeadm@pdb.com'),
       ('Venezuela', 'South America', 'veneadm@pdb.com'),
       ('Vietnam', 'Asia', 'vietadm@pdb.com'),
       ('Vanuatu', 'Oceania', 'vanuadm@pdb.com'),
       ('Yemen', 'Asia', 'yemenadm@pdb.com'),
       ('South Africa', 'Africa', 'soafadm@pdb.com'),
       ('Zambia', 'Africa', 'zambadm@pdb.com'),
       ('Zimbabwe', 'Africa', 'zimbadm@pdb.com');
