platform :ios, '13.0'
workspace 'Pandemica'

target 'Pandemica' do
  use_frameworks!
  pod 'Alamofire', '~> 5.0'
  pod 'SQLite.swift', '~> 0.12.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
